#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 23 17:53:28 2021

@author: lorenzomeloncelli
"""

# We first retrieve the contents from a web ULR using the requests module
import requests
res = requests.get("https://api.artic.edu/api/v1/artworks")

# Then we write the contents to a specific file
file1 =  open("./file-" + "Art-institute-of-chicago" + ".json", "w+")
print(file1)
file1.writelines(res.text)
file1.close()


# Finally we manipulate the data and load them in a dataframe, so that we can use the to_csv() function to create a .csv
import json
import pandas

l = []
dati_json = json.load(open("./file-" + "Art-institute-of-chicago" + ".json"))
for h in dati_json["data"]:
    x = list(h.values())
    l.append(x)
        
csv_file_path = 'Art.csv'
df = pandas.DataFrame(l)
df.to_csv(csv_file_path, sep = ';', index=False)
